# 01 - Mine Dependabot Evidence

This notebook mines repo-level Dependabot evidence for the downstream repositories in the RQ2 pairwise dataset.

It intentionally produces raw evidence only. Classification by adoption date happens in `02_classify_dependabot_usage.ipynb`.

## Inputs and Outputs

Input:

- `../../data/rq2/rq2_master_pairwise.csv`

Outputs:

- `data/dependabot_repo_evidence_raw.csv`
- `data/dependabot_repo_mining_errors.csv`

GitHub authentication:

- Paste a token into the token cell below, or
- Use `GITHUB_TOKEN` from the environment, or
- Fallback to local `.token` in this notebook directory.

## GitHub Token

Paste your GitHub token between the quotes below before running the mining cells. Leave it blank if you want to use `GITHUB_TOKEN` or `.token` instead.

In [18]:
PASTED_GITHUB_TOKEN = ''

In [19]:
from pathlib import Path
import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request

import pandas as pd

ROOT = Path.cwd().parents[1]
INPUT_CSV = ROOT / 'data' / 'rq2' / 'rq2_master_pairwise.csv'
DATA_DIR = ROOT / 'data' / 'rq3'
RAW_EVIDENCE_CSV = DATA_DIR / 'dependabot_repo_evidence_raw.csv'
ERRORS_CSV = DATA_DIR / 'dependabot_repo_mining_errors.csv'

DATA_DIR.mkdir(parents=True, exist_ok=True)

TOKEN_FILE = ROOT / '.token'
if not TOKEN_FILE.exists() and (ROOT / 'dependabot' / '.token').exists():
    TOKEN_FILE = ROOT / 'dependabot' / '.token'

PASTED_TOKEN = globals().get('PASTED_GITHUB_TOKEN', '').strip()
GITHUB_TOKEN = None
TOKEN_SOURCE = None
if PASTED_TOKEN:
    GITHUB_TOKEN = PASTED_TOKEN
    TOKEN_SOURCE = 'PASTED_GITHUB_TOKEN cell'
elif os.environ.get('GITHUB_TOKEN'):
    GITHUB_TOKEN = os.environ['GITHUB_TOKEN'].strip()
    TOKEN_SOURCE = 'GITHUB_TOKEN environment variable'
elif TOKEN_FILE.exists():
    GITHUB_TOKEN = TOKEN_FILE.read_text().strip()
    TOKEN_SOURCE = str(TOKEN_FILE)

if not GITHUB_TOKEN:
    raise RuntimeError('Set PASTED_GITHUB_TOKEN, GITHUB_TOKEN, or create a .token file before running this notebook.')

print(f'Using GitHub token from: {TOKEN_SOURCE}')

REST_API = 'https://api.github.com'
GRAPHQL_API = 'https://api.github.com/graphql'

DEPENDABOT_AUTHORS = [
    'app/dependabot',
    'app/dependabot-preview',
    'dependabot[bot]',
    'dependabot-preview[bot]',
]

CONFIG_PATHS = [
    '.github/dependabot.yml',
    '.github/dependabot.yaml',
]

# Dependabot was introduced in 2017, so ignore impossible earlier evidence.
MIN_DEPENDABOT_EVIDENCE_DATE = '2017-01-01T00:00:00Z'
MIN_DEPENDABOT_SEARCH_DATE = '2017-01-01'

REQUEST_DELAY_SECONDS = 0.2
MAX_RETRIES = 4
REFRESH_EXISTING = False

Using GitHub token from: PASTED_GITHUB_TOKEN cell

## Load and Normalize Repositories

In [20]:
pairs = pd.read_csv(INPUT_CSV)
required_cols = {'CVE', 'upstream_GA', 'downstream_GA', 'downstream_repo', 'commit_url', 'adoption_date'}
missing = required_cols - set(pairs.columns)
if missing:
    raise ValueError(f'Missing required columns: {sorted(missing)}')

def normalize_repo(value):
    if pd.isna(value):
        return None
    text = str(value).strip()
    if not text:
        return None

    text = text.replace('git@github.com:', 'https://github.com/')
    text = text.replace('http://github.com/', 'https://github.com/')
    if text.startswith('https://github.com/'):
        text = text[len('https://github.com/'):]
    if text.startswith('github.com/'):
        text = text[len('github.com/'):]
    text = text.split('#', 1)[0].split('?', 1)[0].strip('/')
    if text.endswith('.git'):
        text = text[:-4]

    parts = [p for p in text.split('/') if p]
    if len(parts) < 2:
        return None
    return f'{parts[0]}/{parts[1]}'

pairs['normalized_downstream_repo'] = pairs['downstream_repo'].map(normalize_repo)
repos = sorted(pairs['normalized_downstream_repo'].dropna().unique())

print(f'Pairwise rows: {len(pairs):,}')
print(f'Unique downstream repositories: {len(repos):,}')
pairs[['downstream_repo', 'normalized_downstream_repo']].drop_duplicates().head()

Pairwise rows: 1,677
Unique downstream repositories: 742

                  downstream_repo      normalized_downstream_repo
0                  btheu/estivate                  btheu/estivate
1                jcabi/jcabi-http                jcabi/jcabi-http
2  ashwanthkumar/gocd-java-client  ashwanthkumar/gocd-java-client
3  grasshopper7/pdfextentreporter  grasshopper7/pdfextentreporter
4    kuehne-trustable-de/ca3sCore    kuehne-trustable-de/ca3sCore

## GitHub API Helpers

In [21]:
def github_headers(extra=None):
    headers = {
        'Authorization': f'Bearer {GITHUB_TOKEN}',
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'rq3-dependabot-miner',
    }
    if extra:
        headers.update(extra)
    return headers

def sleep_for_rate_limit(headers):
    remaining = headers.get('X-RateLimit-Remaining')
    reset = headers.get('X-RateLimit-Reset')
    if remaining == '0' and reset:
        wait = max(0, int(reset) - int(time.time())) + 5
        print(f'Rate limit reached. Sleeping {wait} seconds.')
        time.sleep(wait)

def request_json(url, data=None, method=None):
    body = None
    headers = github_headers()
    if data is not None:
        body = json.dumps(data).encode('utf-8')
        headers['Content-Type'] = 'application/json'

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        req = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=60) as response:
                payload = json.load(response)
                sleep_for_rate_limit(response.headers)
                time.sleep(REQUEST_DELAY_SECONDS)
                return payload, dict(response.headers)
        except urllib.error.HTTPError as exc:
            err_body = exc.read().decode('utf-8', errors='replace')
            last_error = {'status': exc.code, 'body': err_body[:1000], 'url': url}
            if exc.code in {403, 429, 500, 502, 503, 504}:
                sleep_for_rate_limit(exc.headers)
                time.sleep(min(60, 2 ** attempt))
                continue
            raise
        except Exception as exc:
            last_error = {'status': type(exc).__name__, 'body': str(exc), 'url': url}
            time.sleep(min(60, 2 ** attempt))

    raise RuntimeError(f'GitHub request failed after retries: {last_error}')

def graphql(query, variables=None):
    payload = {'query': query, 'variables': variables or {}}
    data, headers = request_json(GRAPHQL_API, data=payload, method='POST')
    if data.get('errors'):
        raise RuntimeError(json.dumps(data['errors'])[:2000])
    return data['data'], headers

## Validate GitHub Token

Run this before the mining loop. A `401 Unauthorized` here means the token is invalid, expired, revoked, copied incorrectly, or not accepted by GitHub for API access.

In [22]:
def validate_github_token():
    try:
        user, _ = request_json(f'{REST_API}/user')
        gql_data, _ = graphql('query { viewer { login } rateLimit { remaining resetAt } }')
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            raise RuntimeError(
                f'GitHub returned 401 Unauthorized for token source: {TOKEN_SOURCE}. '
                'Use a valid, unexpired GitHub token and rerun from the token/setup cells.'
            ) from exc
        raise

    print(f'Authenticated REST user: {user.get("login")}')
    print(f'Authenticated GraphQL user: {gql_data["viewer"]["login"]}')
    print(f'GraphQL remaining requests: {gql_data["rateLimit"]["remaining"]}')

validate_github_token()

Authenticated REST user: kaziamity
Authenticated GraphQL user: kaziamity
GraphQL remaining requests: 4999

## Evidence Mining Functions

In [23]:
FIRST_PR_QUERY = '''
query($q: String!) {
  search(query: $q, type: ISSUE, first: 1) {
    issueCount
    nodes {
      ... on PullRequest {
        createdAt
        number
        title
        url
        author { login }
      }
    }
  }
  rateLimit { cost remaining resetAt }
}
'''

def first_dependabot_pr(repo):
    candidates = []
    searched = []
    for author in DEPENDABOT_AUTHORS:
        search_query = f'repo:{repo} is:pr author:{author} created:>={MIN_DEPENDABOT_SEARCH_DATE} sort:created-asc'
        searched.append(search_query)
        data, _ = graphql(FIRST_PR_QUERY, {'q': search_query})
        nodes = data['search']['nodes']
        if nodes:
            pr = nodes[0]
            candidates.append({
                'createdAt': pr.get('createdAt'),
                'number': pr.get('number'),
                'title': pr.get('title'),
                'url': pr.get('url'),
                'author': (pr.get('author') or {}).get('login'),
                'matched_author_query': author,
                'issueCount': data['search'].get('issueCount'),
            })

    if not candidates:
        return {
            'has_dependabot_pr': False,
            'first_dependabot_pr_date': None,
            'first_dependabot_pr_url': None,
            'first_dependabot_pr_number': None,
            'first_dependabot_pr_author': None,
            'first_dependabot_pr_title': None,
            'first_dependabot_pr_query_author': None,
            'dependabot_pr_search_queries': ' | '.join(searched),
        }

    earliest = sorted(candidates, key=lambda item: item['createdAt'])[0]
    return {
        'has_dependabot_pr': True,
        'first_dependabot_pr_date': earliest['createdAt'],
        'first_dependabot_pr_url': earliest['url'],
        'first_dependabot_pr_number': earliest['number'],
        'first_dependabot_pr_author': earliest['author'],
        'first_dependabot_pr_title': earliest['title'],
        'first_dependabot_pr_query_author': earliest['matched_author_query'],
        'dependabot_pr_search_queries': ' | '.join(searched),
    }

def parse_last_link_page(link_header):
    if not link_header:
        return None
    match = re.search(r'<([^>]+)>;\s*rel="last"', link_header)
    if not match:
        return None
    return match.group(1)

def commits_for_path(repo, path, url=None):
    if url is None:
        encoded_path = urllib.parse.quote(path, safe='')
        since = urllib.parse.quote(MIN_DEPENDABOT_EVIDENCE_DATE, safe='')
        url = f'{REST_API}/repos/{repo}/commits?path={encoded_path}&since={since}&per_page=1'
    return request_json(url)

def first_config_commit_for_path(repo, path):
    data, headers = commits_for_path(repo, path)
    if not data:
        return None

    last_url = parse_last_link_page(headers.get('Link', ''))
    if last_url:
        last_page_data, _ = commits_for_path(repo, path, url=last_url)
        if not last_page_data:
            return None
        commit = last_page_data[-1]
    else:
        commit = data[-1]

    commit_info = commit.get('commit', {})
    return {
        'path': path,
        'sha': commit.get('sha'),
        'html_url': commit.get('html_url'),
        'author_date': (commit_info.get('author') or {}).get('date'),
        'committer_date': (commit_info.get('committer') or {}).get('date'),
        'message': commit_info.get('message'),
    }

def first_dependabot_config(repo):
    candidates = []
    for path in CONFIG_PATHS:
        item = first_config_commit_for_path(repo, path)
        if item:
            candidates.append(item)

    if not candidates:
        return {
            'has_dependabot_config': False,
            'dependabot_config_path': None,
            'dependabot_config_created_date': None,
            'dependabot_config_created_sha': None,
            'dependabot_config_created_url': None,
            'dependabot_config_created_message': None,
        }

    earliest = sorted(candidates, key=lambda item: item.get('committer_date') or item.get('author_date') or '')[0]
    return {
        'has_dependabot_config': True,
        'dependabot_config_path': earliest['path'],
        'dependabot_config_created_date': earliest.get('committer_date') or earliest.get('author_date'),
        'dependabot_config_created_sha': earliest['sha'],
        'dependabot_config_created_url': earliest['html_url'],
        'dependabot_config_created_message': earliest.get('message'),
    }

def mine_repo(repo):
    result = {
        'repo': repo,
        'repo_url': f'https://github.com/{repo}',
        'mined_at_utc': pd.Timestamp.utcnow().isoformat(),
        'mining_status': 'ok',
        'error_type': None,
        'error_message': None,
    }
    result.update(first_dependabot_pr(repo))
    result.update(first_dependabot_config(repo))
    return result

## Resume Cache

In [24]:
if RAW_EVIDENCE_CSV.exists():
    evidence = pd.read_csv(RAW_EVIDENCE_CSV)
else:
    evidence = pd.DataFrame()

if ERRORS_CSV.exists():
    errors = pd.read_csv(ERRORS_CSV)
else:
    errors = pd.DataFrame()

completed = set()
if not evidence.empty and not REFRESH_EXISTING:
    completed.update(evidence.loc[evidence['mining_status'].eq('ok'), 'repo'].dropna())

remaining = [repo for repo in repos if REFRESH_EXISTING or repo not in completed]

print(f'Already mined successfully: {len(completed):,}')
print(f'Remaining repositories: {len(remaining):,}')

Already mined successfully: 0
Remaining repositories: 742

## Run Mining

This cell appends after each repository so the notebook can be stopped and resumed.

In [25]:
def append_csv_row(path, row):
    row_df = pd.DataFrame([row])
    write_header = not path.exists()
    row_df.to_csv(path, mode='a', header=write_header, index=False)

for idx, repo in enumerate(remaining, start=1):
    print(f'[{idx:,}/{len(remaining):,}] {repo}')
    try:
        row = mine_repo(repo)
        append_csv_row(RAW_EVIDENCE_CSV, row)
    except Exception as exc:
        err = {
            'repo': repo,
            'repo_url': f'https://github.com/{repo}',
            'mined_at_utc': pd.Timestamp.utcnow().isoformat(),
            'mining_status': 'error',
            'error_type': type(exc).__name__,
            'error_message': str(exc)[:2000],
        }
        append_csv_row(ERRORS_CSV, err)
        print(f'  ERROR: {err["error_type"]}: {err["error_message"][:300]}')

[1/742] 42BV/jarb
[2/742] 52North/arctic-sea
[3/742] 52North/series-hibernate
[4/742] 6tail/nlf2-maven
[5/742] 88250/latke
[6/742] AKSW/jena-sparql-api
[7/742] Activiti/Activiti
[8/742] AlejandroRivera/embedded-rabbitmq
[9/742] AmyAssist/Amy
[10/742] AquaticInformatics/aquarius-sdk-java
[11/742] ArcBees/GWTP
[12/742] ArcadeData/arcade-connectors
[13/742] AsyncHttpClient/async-http-client
[14/742] AthenZ/athenz
[15/742] AxonFramework/AxonFramework
[16/742] Axway/ats-framework
[17/742] Azure/azure-sdk-for-java
[18/742] Baidu-ecom/Jprotobuf-rpc-socket
[19/742] BaseXdb/basex
[20/742] Bedework/bw-calendar-engine
[21/742] Bedework/bw-event-registration
[22/742] Bedework/bw-synch
[23/742] BroadleafCommerce/BroadleafCommerce
[24/742] BrunoEberhard/minimal-j
[25/742] Bynder/bynder-java-sdk
[26/742] CAFAudit/audit-service
[27/742] Captain-P-Goldfish/SCIM
[28/742] CloudSlang/cloud-slang
[29/742] CloudSlang/cs-actions
[30/742] CloudSlang/score
[31/742] Comcast/jrugged
[32/742] ConsumerDataStandardsAustralia/java-artefacts
[33/742] Contrast-Security-OSS/contrast-maven-plugin
[34/742] Coreoz/Wisp
[35/742] Crim/pardot-java-client
[36/742] CyberSource/cybersource-sdk-java
[37/742] CycloneDX/cyclonedx-core-java
[38/742] DDTH/ddth-commons
[39/742] DSpace/DSpace
[40/742] DataSketches/sketches-hive
[41/742] DataSketches/sketches-pig
[42/742] DataSystemsLab/GeoSpark
[43/742] DigitalPebble/storm-crawler
[44/742] DisneyStudios/cucumber-slices-maven-plugin
[45/742] Dreamroute/locker
[46/742] Erudika/para
[47/742] EvoSuite/evosuite
[48/742] ExpediaGroup/circus-train
[49/742] ExpediaGroup/waggle-dance
[50/742] FelixGail/gplaymusic
[51/742] GSI-CS-CO/chart-fx
[52/742] GateNLP/gate-core
[53/742] GeoDienstenCentrum/schemaspy-maven-plugin
[54/742] GojaFramework/goja
[55/742] GoogleCloudPlatform/bigdata-interop
[56/742] GraphWalker/graphwalker-project
[57/742] Graylog2/graylog2-server
[58/742] HotelsDotCom/beeju
[59/742] HotelsDotCom/corc
[60/742] HotelsDotCom/data-highway
[61/742] Huanying04/jixiv
[62/742] Huluvu424242/plantuml-maven-plugin
[63/742] ICIJ/extract
[64/742] INL/BlackLab
[65/742] INRIA/spoon
[66/742] Impetus/fabric-jdbc-connector
[67/742] JULIELab/costosys
[68/742] JULIELab/jcore-dependencies
[69/742] JanusGraph/janusgraph
[70/742] Jasig/person-directory
[71/742] KleeGroup/vertigo
[72/742] LevelFourAB/dust
[73/742] Litote/kmongo
[74/742] Loki-Afro/metalarchives
[75/742] LucidWorks/spark-solr
[76/742] Mercateo/rest-schemagen-spring
[77/742] MingweiSamuel/Zyra
[78/742] ModeShape/modeshape
[79/742] MyCoRe-Org/mycore
[80/742] NASA-PDS-Incubator/registry
[81/742] NitorCreations/nflow
[82/742] NitorCreations/willow
[83/742] Olog/phoebus-olog
[84/742] OpenAS2/OpenAs2App
[85/742] OpenSextant/Xponents
[86/742] OrbitzWorldwide/consul-client
[87/742] OrderOfTheBee/ootbee-support-tools
[88/742] OrienteerBAP/Orienteer
[89/742] OxalisCommunity/oxalis
[90/742] Pay-Group/best-pay-sdk
[91/742] PennState/commons-jaxrs
[92/742] PgBulkInsert/PgBulkInsert
[93/742] RIPE-NCC/rpki-commons
[94/742] Red5/red5-websocket
[95/742] RedCA-Family/code-analyst
[96/742] Relucent/yyl-base-lib
[97/742] RockyLOMO/rxlib
[98/742] RuedigerMoeller/kontraktor
[99/742] SANSA-Stack/SANSA-OWL
[100/742] ServiceComb/java-chassis
[101/742] Sila-Money/sila-sdk-java
[102/742] SimonAlong/Neo
[103/742] Smartling/api-sdk-java
[104/742] SoftInstigate/restheart
[105/742] SonarCommunity/sonar-php
[106/742] SonarSource/orchestrator
[107/742] SonarSource/sonar-findbugs
[108/742] SparkTC/stocator
[109/742] SpringSource/spring-ldap
[110/742] SuperScorpion/medusa
[111/742] TNG/config-builder
[112/742] TheBlackChamber/commons-encryption
[113/742] Tirasa/ConnIdSOAPBundle
[114/742] UweTrottmann/thetvdb-java
[115/742] UweTrottmann/tmdb-java
[116/742] UweTrottmann/trakt-java
[117/742] Waffle/waffle
[118/742] Wikidata/Wikidata-Toolkit
[119/742] Xceptance/XLT
[120/742] XenoAmess/docker-client
[121/742] Zandero/rest.vertx
[122/742] Zlika/reproducible-build-maven-plugin
[123/742] aQute-os/biz.aQute.openapi
[124/742] acegi/xml-format-maven-plugin
[125/742] actframework/actframework
[126/742] aerogear/aerogear-unifiedpush-server
[127/742] aerospike/aerospike-client-java
[128/742] airlift/airlift
[129/742] aktin/broker
[130/742] alexcojocaru/elasticsearch-maven-plugin
[131/742] alexxiyang/shiro-redis
[132/742] algolia/algoliasearch-client-java-2
[133/742] alibaba/Sentinel
[134/742] alibaba/canal
[135/742] alibaba/druid
[136/742] alluxio/alluxio
[137/742] almex/Raildelays
[138/742] americanexpress/synapse
[139/742] annot8/annot8-components
[140/742] anotheria/ano-util
[141/742] anotheria/moskito
[142/742] aoju/bus
[143/742] apache/airavata
[144/742] apache/any23
[145/742] apache/avro
[146/742] apache/bookkeeper
[147/742] apache/flink
[148/742] apache/incubator-dubbo
[149/742] apache/incubator-nlpcraft
[150/742] apache/incubator-plc4x
[151/742] apache/juneau
[152/742] apache/openmeetings
[153/742] apache/parquet-mr
[154/742] apache/plc4x
[155/742] apache/ranger
[156/742] apache/reef
[157/742] apache/royale-compiler
[158/742] apicurio/apicurio-registry
[159/742] apigee/apigee-config-maven-plugin
[160/742] apigee/apigee-smartdocs-maven-plugin
[161/742] appNG/appng
[162/742] appNG/appng-scheduler
[163/742] archiecobbs/dellroad-stuff
[164/742] archiecobbs/jsimpledb
[165/742] archivesunleashed/aut
[166/742] arenadata/hive
[167/742] arpnetworking/commons
[168/742] arpnetworking/logback-steno
[169/742] arpnetworking/metrics-cluster-aggregator
[170/742] ashwanthkumar/gocd-java-client
[171/742] aspectran/aspectran
[172/742] astrapi69/jetty-runner
[173/742] astrapi69/mystic-crypt
[174/742] astrapi69/spring-tool-extensions
[175/742] automatiko-io/automatiko-engine
[176/742] awslabs/amazon-kinesis-client
[177/742] baayso/commons
[178/742] basestar/basestar
[179/742] bcgov/cpf
[180/742] beangle/beangle3
[181/742] bedrin/kerb4j
[182/742] benas/easy-batch
[183/742] binfalse/ModelCrawler
[184/742] bitblit/wrench
[185/742] bjuvensjo/rsimulator
[186/742] bld-commons/dev-excel
[187/742] blinkfox/jpack-maven-plugin
[188/742] blossom-project/blossom
[189/742] bonigarcia/selenium-jupiter
[190/742] bonitasoft/bonita-engine
[191/742] bootique/bootique-shiro
[192/742] borball/weixin-sdk
[193/742] bsorrentino/maven-confluence-plugin
[194/742] btc-ag/redg
[195/742] btheu/estivate
[196/742] btrplace/scheduler
[197/742] bujiio/buji-pac4j
[198/742] caelum/vraptor4
[199/742] camel-extra/camel-extra
[200/742] camunda-community-hub/zeebe-exporter-protobuf
[201/742] carewebframework/carewebframework-core
[202/742] carrot2/elasticsearch-carrot2
[203/742] caskdata/cdap
[204/742] cassandre-tech/cassandre-trading-bot
[205/742] cerner/beadledom
[206/742] chainsql/java-chainsql-api
[207/742] charithe/kafka-junit
[208/742] chelu/jdal
[209/742] cheny2151/toolbox
[210/742] chhorz/oas-generator
[211/742] chilloutdevelopment/pl.chilldev.commons
[212/742] christian-schlichtherle/truelicense
[213/742] citrusframework/citrus
[214/742] claudius108/kuberam-expath-plugin
[215/742] cloud-of-things/cot-java-rest-sdk
[216/742] cloudfoundry/cf-java-client
[217/742] cmake-maven-project/cmake-maven-project
[218/742] codahale/xsalsa20poly1305
[219/742] code4craft/xsoup
[220/742] codelibs/elasticsearch-analysis-extension
[221/742] codelibs/elasticsearch-analysis-fess
[222/742] codelibs/elasticsearch-analysis-ja
[223/742] codelibs/elasticsearch-analysis-kuromoji-neologd
[224/742] codelibs/elasticsearch-cluster-runner
[225/742] codelibs/elasticsearch-configsync
[226/742] codelibs/elasticsearch-dataformat
[227/742] codelibs/elasticsearch-dynarank
[228/742] codelibs/elasticsearch-lang-velocity
[229/742] codelibs/elasticsearch-minhash
[230/742] codelibs/elasticsearch-solr-api
[231/742] codelibs/elasticsearch-sstmpl
[232/742] codelibs/elasticsearch-taste
[233/742] codelibs/fess-crawler
[234/742] codelibs/fess-ds-atlassian
[235/742] codelibs/fess-ds-csv
[236/742] codelibs/fess-ds-db
[237/742] codelibs/fess-ds-elasticsearch
[238/742] codelibs/fess-ds-gitbucket
[239/742] codelibs/fess-ds-gsuite
[240/742] codemonstur/HTMLCompiler
[241/742] codescape/bitvunit
[242/742] cofcool/chaos-server
[243/742] cometd/cometd
[244/742] commercetools/commercetools-jvm-sdk
[245/742] confluentinc/parallel-consumer
[246/742] contentful/contentful-management.java
[247/742] contentful/contentful.java
[248/742] conveyal/r5
[249/742] cose-wg/cose-java
[250/742] couchbase/kafka-connect-couchbase
[251/742] craftercms/core
[252/742] craftercms/profile
[253/742] craftercms/search
[254/742] credibledoc/credible-doc
[255/742] cryptomator/siv-mode
[256/742] cryptomator/webdav-nio-adapter
[257/742] ctron/rpm-builder
[258/742] cucumber/cucumber-jvm
[259/742] dadoonet/fscrawler
[260/742] dadoonet/rssriver
[261/742] dadoonet/spring-elasticsearch
[262/742] damiencarol/jsr203-hadoop
[263/742] datasonnet/datasonnet-mapper
[264/742] datastax/simulacron
[265/742] davidcarboni/Cryptolite
[266/742] davidkarlsen/Commons-Transaction-Spring-Integration
[267/742] dblock/waffle
[268/742] dbmdz/cudami
[269/742] dbmdz/digitalcollections-model
[270/742] dbmdz/iiif-apis
[271/742] dbmdz/iiif-bookshelf-webapp
[272/742] dbmdz/iiif-server-hymir
[273/742] de4a-wp5/de4a-commons
[274/742] debezium/debezium
[275/742] deeplearning4j/deeplearning4j
[276/742] dekorateio/dekorate
[277/742] dernasherbrezon/deb-maven-plugin
[278/742] detectiveframework/detective
[279/742] devlibx/easy
[280/742] dgroup/docker-unittests
[281/742] dickschoeller/gedbrowser
[282/742] diennea/blazingcache
[283/742] diennea/blobit
[284/742] difi/oxalis
[285/742] difi/sikker-digital-post-klient
[286/742] digipost/certificate-validator
[287/742] digipost/digipost-api-client-java
[288/742] digital-preservation/droid
[289/742] dkpro/dkpro-core
[290/742] dmandalidis/docker-client
[291/742] dnsjava/dnsjava
[292/742] docker-java/docker-java
[293/742] dracoon/dracoon-java-sdk
[294/742] drasyl-overlay/drasyl
[295/742] dromara/hutool
[296/742] druid-io/druid
[297/742] dts-ait/ariadne-json-route-format
[298/742] duracloud/duracloud
[299/742] duracloud/duracloud-db
[300/742] duracloud/snapshot
[301/742] dustin-johnson/timezonemap
[302/742] dwslab/melt
[303/742] eclipse-ee4j/glassfish
[304/742] eclipse/deeplearning4j
[305/742] eclipse/hono
[306/742] egetman/jes
[307/742] egzosn/pay-java-parent
[308/742] ehrbase/ehrbase
[309/742] eirslett/frontend-maven-plugin
[310/742] electronicarts/ea-async
[311/742] englishtown/vertx-mod-elasticsearch
[312/742] enioka/jqm
[313/742] entur/mapstruct-spi-protobuf
[314/742] envoyproxy/protoc-gen-validate
[315/742] erudika/para-dao-sql
[316/742] esaulpaugh/headlong
[317/742] esbtools/esb-message-admin
[318/742] eu-emi/canl-java
[319/742] euler-projects/euler-framework
[320/742] evanchooly/bottlerocket
[321/742] excelsior-oss/restler
[322/742] exist-db/exist
[323/742] fabric8io/elasticsearch-cloud-kubernetes
[324/742] fabric8io/fabric8
[325/742] fabric8io/kubernetes-client
[326/742] factcast/factcast
[327/742] fartherp/framework
[328/742] fastjrun/sdkg
[329/742] fcrepo-exts/fcrepo-camel
[330/742] fcrepo-exts/fcrepo-camel-toolbox
[331/742] fcrepo/fcrepo
[332/742] fcrepo3/fcrepo
[333/742] fcrepo4-exts/fcrepo-camel-toolbox
[334/742] fedora-java/xmvn
[335/742] felleslosninger/efm-integrasjonspunkt
[336/742] fidusio/zoxweb-core
[337/742] fizzed/stork
[338/742] flapdoodle-oss/de.flapdoodle.embed.process
[339/742] flowable/flowable-engine
[340/742] flowlogix/flowlogix
[341/742] fluo-io/fluo
[342/742] flyingsaucerproject/flyingsaucer
[343/742] flyway/flyway
[344/742] freedomotic/freedomotic
[345/742] fuinorg/event-store-maven-plugin
[346/742] fujion/fujion-framework
[347/742] furkandogan/web-automation-template
[348/742] g-research/siembol
[349/742] galan/commons
[350/742] galasa-dev/framework
[351/742] geolatte/geolatte-geom
[352/742] geomajas/geomajas-project-client-gwt
[353/742] georgberky/dependency-update-maven-plugin
[354/742] gismaker/lambkit
[355/742] godaddy/asherah
[356/742] goldmansachs/obevo
[357/742] google/tink
[358/742] graphaware/neo4j-framework
[359/742] graphhopper/graphhopper
[360/742] grasshopper7/cucumber-pdf-report
[361/742] grasshopper7/pdfextentreporter
[362/742] gudaoxuri/dew-common
[363/742] gzxishan/OftenPorter
[364/742] hammock-project/hammock
[365/742] hapifhir/hapi-fhir
[366/742] hazelcast/hazelcast-simulator
[367/742] hazendaz/displaytag
[368/742] hcoles/pitest
[369/742] helun/Ektorp
[370/742] heroku/heroku-maven-plugin
[371/742] heuermh/dishevelled
[372/742] hibernate/hibernate-ogm
[373/742] holon-platform/holon-core
[374/742] huaweicloud/huaweicloud-sdk-java-dis
[375/742] hugegraph/hugegraph-loader
[376/742] hydrator/wrangler
[377/742] hyperchain/javasdk
[378/742] hypercube1024/firefly
[379/742] hyperledger/fabric-sdk-java
[380/742] iZettle/dropwizard-metrics-influxdb
[381/742] idflakies/iDFlakies
[382/742] iitsoftware/swiftmq-client
[383/742] ijazfx/graphenee
[384/742] ikasanEIP/ikasan
[385/742] in-toto/in-toto-java
[386/742] infinispan/infinispan
[387/742] influxdata/influxdb-java
[388/742] inspire-software/geda-genericdto
[389/742] intelligentcode/ameba-shiro
[390/742] internetarchive/heritrix3
[391/742] iotaledger/iota-java
[392/742] j-easy/easy-batch
[393/742] jOOQ/jOOQ
[394/742] jamesdbloom/mockservice
[395/742] javalite/activejdbc
[396/742] javamelody/javamelody
[397/742] javawebers/yt
[398/742] jayway/powermock
[399/742] jbake-org/jbake-maven-plugin
[400/742] jbehave/jbehave-core
[401/742] jbossas/jboss-invocation
[402/742] jbossas/remoting-jmx
[403/742] jbossws/jbossws-cxf
[404/742] jcabi/jcabi-http
[405/742] jdillon/mvnsh
[406/742] jefalbino/jsmart-web
[407/742] jeremylong/DependencyCheck
[408/742] jhannes/logevents
[409/742] jhipster/jhipster
[410/742] jitsi/jitsi-srtp
[411/742] jitsi/zrtp4j
[412/742] jituancaiyun/openapi-java-sdk
[413/742] jjYBdx4IL/misc
[414/742] jnidzwetzki/bboxdb
[415/742] jnoee/coo
[416/742] joniles/mpxj
[417/742] jooby-project/jooby
[418/742] joyent/java-http-signature
[419/742] jqassistant/jqa-neo4j-backend
[420/742] jqassistant/jqa-plugin-common
[421/742] jsonld-java/jsonld-java
[422/742] jspare-projects/vertx-jspare
[423/742] jsunsoftware/http-request
[424/742] jsurfer/JsonSurfer
[425/742] junaidontable/baltoro.lib
[426/742] jwcarman/Wicketopia
[427/742] kawansoft/aceql-http
[428/742] ketola/jlibra
[429/742] keycloak/keycloak
[430/742] kiegroup/kogito-runtimes
[431/742] kiegroup/optaplanner
[432/742] kiwiproject/kiwi
[433/742] klarna/HiveRunner
[434/742] kohlschutter/junixsocket
[435/742] kokuwaio/helm-maven-plugin
[436/742] konigio/konig
[437/742] korpling/ANNIS
[438/742] kristofa/brave
[439/742] kse-music/mcn-boot-project
[440/742] kubernetes-client/java
[441/742] kuehne-trustable-de/ca3sCore
[442/742] labai/ted
[443/742] languagetool-org/languagetool
[444/742] lazy-koala/java-toolkit
[445/742] liaochong/myexcel
[446/742] librespot-org/librespot-java
[447/742] liferay/portletmvc4spring
[448/742] lightblueseas/email-tails
[449/742] lijiahangmax/orion-kit
[450/742] linqs/psl
[451/742] lionsoul2014/jcseg
[452/742] liquibase/liquibase-cache
[453/742] liquibase/liquibase-cosmosdb
[454/742] liquibase/liquibase-db2i
[455/742] liquibase/liquibase-filechangelog
[456/742] lithiumtech/flow
[457/742] logfellow/logstash-logback-encoder
[458/742] logzio/sawmill
[459/742] luisgoncalves/xades4j
[460/742] lukas-krecan/smock
[461/742] mangstadt/ez-vcard
[462/742] marcust/jzenith
[463/742] marklogic/marklogic-contentpump
[464/742] martinpaljak/GlobalPlatformPro
[465/742] matjaz99/alertmonitor
[466/742] maxmind/minfraud-api-java
[467/742] mbizhani/Wickomp
[468/742] mcollovati/vertx-vaadin
[469/742] mediathekview/MLib
[470/742] mercibe/jxsl
[471/742] messagebird/java-rest-api
[472/742] mhradek/aurkitu
[473/742] mike10004/har-replay
[474/742] miltonio/milton2
[475/742] mizool/mizool
[476/742] mkolisnyk/cucumber-reports
[477/742] mnemonic-no/messaging
[478/742] molindo/esi4j
[479/742] mrami4/bluecircle-json-interface-generator
[480/742] mrniko/netty-socketio
[481/742] msoute/vertx-deploy-mod
[482/742] mulesoft/mule
[483/742] mulesoft/mule-soap-service
[484/742] mybatis/guice
[485/742] mybatis/spring
[486/742] mybatis/spring-boot-starter
[487/742] mybatis/velocity-scripting
[488/742] nasa-pds/pds4-information-model
[489/742] naspart/wx-tools
[490/742] nbbrd/spreadsheet4j
[491/742] neo4j/licensing-maven-plugin
[492/742] neo4j/neo4j
[493/742] netty/netty
[494/742] networknt/light-4j
[495/742] networknt/light-graphql-4j
[496/742] networknt/light-hybrid-4j
[497/742] networknt/light-kafka
[498/742] networknt/light-rest-4j
[499/742] networknt/light-session-4j
[500/742] networknt/light-spa-4j
[501/742] ngrondin/firebus
[502/742] nicho92/mkm-api-java
[503/742] nielsbasjes/logparser
[504/742] ninjaframework/ninja
[505/742] noear/solon
[506/742] nom-tam-fits/nom-tam-fits
[507/742] nosan/embedded-cassandra
[508/742] nscuro/webdriver-manager
[509/742] nuls-io/nuls-v2
[510/742] nutzam/nutzboot
[511/742] nutzam/nutzmore
[512/742] obase/java
[513/742] oboehm/PatternTesting2
[514/742] ocpsoft/prettytime
[515/742] officefloor/OfficeFloor
[516/742] open-eid/digidoc4j
[517/742] opencast/opencast
[518/742] opendistro-for-elasticsearch/security
[519/742] openl-tablets/openl-tablets
[520/742] openshift/openshift-restclient-java
[521/742] opentelecoms-org/gsm0348
[522/742] opentripplanner/OpenTripPlanner
[523/742] orbisgis/H2GIS
[524/742] oscerd/camel-cassandra
[525/742] ozsie/detekt-maven-plugin
[526/742] pac4j/pac4j
[527/742] pac4j/play-pac4j
[528/742] pac4j/spark-pac4j
[529/742] pac4j/spring-security-pac4j
[530/742] paseto-toolkit/jpaseto
[531/742] paul-hammant/servirtium
[532/742] performancecopilot/parfait
[533/742] permazen/permazen
[534/742] perwendel/spark
[535/742] petalslink/flowable-engine
[536/742] petergeneric/stdlib
[537/742] phax/peppol-smp-server
[538/742] phax/ph-commons
[539/742] phax/ph-ebinterface
[540/742] pietermartin/sqlg
[541/742] pinterest/secor
[542/742] pippo-java/pippo
[543/742] platformsh/config-reader-java
[544/742] playframework/netty-reactive-streams
[545/742] playn/playn
[546/742] powermock/powermock
[547/742] powertac/powertac-core
[548/742] powertac/powertac-server
[549/742] powsybl/powsybl-core
[550/742] premium-minds/billy
[551/742] prestodb/presto-hive-apache
[552/742] prestosql/presto
[553/742] prestosql/presto-hive-apache
[554/742] project-ncl/sourceclear-invoker
[555/742] projectnessie/nessie
[556/742] psi-probe/psi-probe
[557/742] pugwoo/woo-utils
[558/742] quarkusio/quarkus
[559/742] qubole/rubix
[560/742] quickfix-j/quickfixj
[561/742] qwazr/library-modules
[562/742] r2dbc/r2dbc-h2
[563/742] rabbitmq/hop
[564/742] rahulsinghai/logback-kafka-appender
[565/742] ralscha/sse-eventbus
[566/742] rapid7/docker-image-analyzer
[567/742] rapidoid/rapidoid
[568/742] raydac/mvn-golang
[569/742] raydac/mvn-jlink
[570/742] rayokota/kareldb
[571/742] rayokota/kcache
[572/742] release-engineering/koji-build-finder
[573/742] research-virtualfortknox/msb-client-websocket-java
[574/742] researchstudio-sat/webofneeds
[575/742] restx/restx
[576/742] restx/restx-shell
[577/742] revelc/formatter-maven-plugin
[578/742] rfoltyns/log4j2-elasticsearch
[579/742] richardwilly98/elasticsearch-river-mongodb
[580/742] rocketbase-io/commons-asset
[581/742] rubenlagus/TelegramBots
[582/742] s-frei/TrackSearch
[583/742] sakaiproject/sakai
[584/742] sangupta/jerry-core
[585/742] sbabcoc/Settings
[586/742] sbmlteam/jsbml
[587/742] searls/jasmine-maven-plugin
[588/742] sebthom/oval
[589/742] sendgrid/sendgrid-java
[590/742] serenity-bdd/serenity-core
[591/742] seznam/euphoria
[592/742] shalousun/ApplicationPower
[593/742] shiruka/api
[594/742] shred/acme4j
[595/742] simplyti/simple-server
[596/742] sitture/env-config
[597/742] skbkontur/extern-java-sdk
[598/742] smooks/smooks
[599/742] snyk/snyk-maven-plugin
[600/742] soasada/popok
[601/742] softelnet/sponge
[602/742] sokomishalov/skraper
[603/742] solr-cool/solr-analyzers
[604/742] solr-cool/solr-thymeleaf
[605/742] solr-cool/solr-util
[606/742] sonallux/spotify-web-api
[607/742] spdx/LicenseListPublisher
[608/742] spdx/tools
[609/742] spotbugs/sonar-findbugs

## Quick Summary

In [26]:
evidence = pd.read_csv(RAW_EVIDENCE_CSV) if RAW_EVIDENCE_CSV.exists() else pd.DataFrame()
errors = pd.read_csv(ERRORS_CSV) if ERRORS_CSV.exists() else pd.DataFrame()

print(f'Evidence rows: {len(evidence):,}')
print(f'Error rows: {len(errors):,}')

if not evidence.empty:
    print('\nDependabot PR evidence:')
    print(evidence['has_dependabot_pr'].value_counts(dropna=False))
    print('\nDependabot config evidence:')
    print(evidence['has_dependabot_config'].value_counts(dropna=False))
    display(evidence.head())

if not errors.empty:
    print('\nTop error types:')
    print(errors['error_type'].value_counts(dropna=False).head(10))
    display(errors.head())

Evidence rows: 742
Error rows: 443

Dependabot PR evidence:
has_dependabot_pr
True     545
False    197
Name: count, dtype: int64

Dependabot config evidence:
has_dependabot_config
False    533
True     209
Name: count, dtype: int64

,repo,repo_url,mined_at_utc,mining_status,error_type,error_message,has_dependabot_pr,first_dependabot_pr_date,first_dependabot_pr_url,first_dependabot_pr_number,first_dependabot_pr_author,first_dependabot_pr_title,first_dependabot_pr_query_author,dependabot_pr_search_queries,has_dependabot_config,dependabot_config_path,dependabot_config_created_date,dependabot_config_created_sha,dependabot_config_created_url,dependabot_config_created_message
0,42BV/jarb,https://github.com/42BV/jarb,2026-08-14T17:00:36.520962+00:00,ok,NaN,NaN,True,2020-01-21T21:11:51Z,https://github.com/42BV/jarb/pull/53,53.0,dependabot,Bump spring.version from 5.1.3.RELEASE to 5.2....,app/dependabot,repo:42BV/jarb is:pr author:app/dependabot cre...,False,NaN,NaN,NaN,NaN,NaN
1,52North/arctic-sea,https://github.com/52North/arctic-sea,2026-08-14T17:00:42.593324+00:00,ok,NaN,NaN,True,2019-08-01T21:59:32Z,https://github.com/52North/arctic-sea/pull/47,47.0,dependabot,Bump version.jackson from 2.9.9 to 2.10.0.pr1,app/dependabot,repo:52North/arctic-sea is:pr author:app/depen...,True,.github/dependabot.yml,2021-04-29T15:25:46Z,fe7416a0a9a56c960616fe58de41f1e5b0e19049,https://github.com/52North/arctic-sea/commit/f...,Upgrade to GitHub-native Dependabot
2,52North/series-hibernate,https://github.com/52North/series-hibernate,2026-08-14T17:00:50.205286+00:00,ok,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,repo:52North/series-hibernate is:pr author:app...,True,.github/dependabot.yml,2021-04-29T15:25:57Z,924fab33f054d8521a2e2ade95609ec9f0aba51b,https://github.com/52North/sensorweb-server-db...,Upgrade to GitHub-native Dependabot
3,6tail/nlf2-maven,https://github.com/6tail/nlf2-maven,2026-08-14T17:00:59.268097+00:00,ok,NaN,NaN,True,2019-10-29T21:06:00Z,https://github.com/6tail/nlf2-maven/pull/1,1.0,dependabot,Bump c3p0 from 0.9.5.2 to 0.9.5.4 in /nlf2-plu...,app/dependabot,repo:6tail/nlf2-maven is:pr author:app/dependa...,False,NaN,NaN,NaN,NaN,NaN
4,88250/latke,https://github.com/88250/latke,2026-08-14T17:01:06.101623+00:00,ok,NaN,NaN,True,2021-02-08T21:25:30Z,https://github.com/88250/latke/pull/37,37.0,dependabot,⬆️ Bump netty.version from 4.1.49.Final to 4.1...,app/dependabot,repo:88250/latke is:pr author:app/dependabot c...,False,NaN,NaN,NaN,NaN,NaN

Top error types:
error_type
HTTPError    443
Name: count, dtype: int64

,repo,repo_url,mined_at_utc,mining_status,error_type,error_message
0,42BV/jarb,https://github.com/42BV/jarb,2026-08-14T16:55:34.850082+00:00,error,HTTPError,HTTP Error 401: Unauthorized
1,52North/arctic-sea,https://github.com/52North/arctic-sea,2026-08-14T16:55:35.068779+00:00,error,HTTPError,HTTP Error 401: Unauthorized
2,52North/series-hibernate,https://github.com/52North/series-hibernate,2026-08-14T16:55:35.384423+00:00,error,HTTPError,HTTP Error 401: Unauthorized
3,6tail/nlf2-maven,https://github.com/6tail/nlf2-maven,2026-08-14T16:55:35.636576+00:00,error,HTTPError,HTTP Error 401: Unauthorized
4,88250/latke,https://github.com/88250/latke,2026-08-14T16:55:35.826828+00:00,error,HTTPError,HTTP Error 401: Unauthorized