In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/rq1/corrected_resolved_links_v2.csv')
df.head()

,CVE_ID,Commit Message,Links in Message,Link Presence,PATCH
0,CVE-2013-4600,Fixed some XSS problems (github issue #173),https://github.com/alkacon/opencms-core/issues...,contains links,https://github.com/alkacon/opencms-core/commit...
1,CVE-2018-3831,Apply settings filter to get cluster settings ...,https://github.com/elastic/elasticsearch/pull/...,contains links,https://github.com/elastic/elasticsearch/commi...
2,CVE-2013-4310,Changes archetypes version to match latest rel...,https://svn.apache.org/repos/asf/struts/struts...,contains links,https://github.com/apache/struts/commit/0c8366...
3,CVE-2018-1000615,"Fix for OS-12, NumberFormatException on badly ...",NaN,no links,https://github.com/opennetworkinglab/onos/comm...
4,CVE-2022-23596,fix: invalid subheader type would throw npe an...,https://github.com/junrar/junrar/issues/73,contains links,https://github.com/junrar/junrar/commit/7b16b3...

In [3]:
# df contains cve id, associated commit message. Here, the link presence represents whether the patch contains a link or not. THis is called transparent fix.

In [4]:
df['CVE_ID'].nunique()

832

In [5]:
import re
def extract_repo(patch):
    # This regex captures the 'user/repository' part from a GitHub URL.
    pattern = r'https://github\.com/([^/]+/[^/\s]+)'
    match = re.search(pattern, patch)
    return match.group(1) if match else None

# Create a new column 'repository' using the above extraction function.
df['repository'] = df['PATCH'].apply(lambda x: extract_repo(x) if pd.notnull(x) else None)
df

,CVE_ID,Commit Message,Links in Message,Link Presence,PATCH,repository
0,CVE-2013-4600,Fixed some XSS problems (github issue #173),https://github.com/alkacon/opencms-core/issues...,contains links,https://github.com/alkacon/opencms-core/commit...,alkacon/opencms-core
1,CVE-2018-3831,Apply settings filter to get cluster settings ...,https://github.com/elastic/elasticsearch/pull/...,contains links,https://github.com/elastic/elasticsearch/commi...,elastic/elasticsearch
2,CVE-2013-4310,Changes archetypes version to match latest rel...,https://svn.apache.org/repos/asf/struts/struts...,contains links,https://github.com/apache/struts/commit/0c8366...,apache/struts
3,CVE-2018-1000615,"Fix for OS-12, NumberFormatException on badly ...",NaN,no links,https://github.com/opennetworkinglab/onos/comm...,opennetworkinglab/onos
4,CVE-2022-23596,fix: invalid subheader type would throw npe an...,https://github.com/junrar/junrar/issues/73,contains links,https://github.com/junrar/junrar/commit/7b16b3...,junrar/junrar
...,...,...,...,...,...,...
827,CVE-2021-39139,Switch to whitelist by default.,NaN,no links,https://github.com/x-stream/xstream/commit/652...,x-stream/xstream
828,CVE-2014-3529,not found,NaN,contains links,https://github.com/apache/poi/commit/103b45073...,apache/poi
829,CVE-2013-2071,Fix https://issues.apache.org/bugzilla/show_bu...,https://issues.apache.org/bugzilla/show_bug.cg...,contains links,https://github.com/apache/tomcat/commit/4171baf,apache/tomcat
830,CVE-2018-1284,HIVE-18879: Disallow embedded element in UDFXP...,NaN,contains links,https://github.com/apache/hive/commit/f80a38ae...,apache/hive
831,CVE-2011-3923,Fixed a security issue (see [1] for further de...,https://cwiki.apache.org/confluence/display/WW...,contains links,https://github.com/apache/struts/commit/2c1eb6...,apache/struts

In [6]:
df['repository'].nunique()

257

In [7]:
# this says all 832 cves are coming from 257 repos.

In [8]:
df['Link Presence'].value_counts()

Link Presence
contains links    471
no links          361
Name: count, dtype: int64

In [9]:
# this means that 471 are transparent fix. and 361 is silent fix.

In [10]:
#among the transparent fix, check the reporting characteristics.

In [11]:
df

,CVE_ID,Commit Message,Links in Message,Link Presence,PATCH,repository
0,CVE-2013-4600,Fixed some XSS problems (github issue #173),https://github.com/alkacon/opencms-core/issues...,contains links,https://github.com/alkacon/opencms-core/commit...,alkacon/opencms-core
1,CVE-2018-3831,Apply settings filter to get cluster settings ...,https://github.com/elastic/elasticsearch/pull/...,contains links,https://github.com/elastic/elasticsearch/commi...,elastic/elasticsearch
2,CVE-2013-4310,Changes archetypes version to match latest rel...,https://svn.apache.org/repos/asf/struts/struts...,contains links,https://github.com/apache/struts/commit/0c8366...,apache/struts
3,CVE-2018-1000615,"Fix for OS-12, NumberFormatException on badly ...",NaN,no links,https://github.com/opennetworkinglab/onos/comm...,opennetworkinglab/onos
4,CVE-2022-23596,fix: invalid subheader type would throw npe an...,https://github.com/junrar/junrar/issues/73,contains links,https://github.com/junrar/junrar/commit/7b16b3...,junrar/junrar
...,...,...,...,...,...,...
827,CVE-2021-39139,Switch to whitelist by default.,NaN,no links,https://github.com/x-stream/xstream/commit/652...,x-stream/xstream
828,CVE-2014-3529,not found,NaN,contains links,https://github.com/apache/poi/commit/103b45073...,apache/poi
829,CVE-2013-2071,Fix https://issues.apache.org/bugzilla/show_bu...,https://issues.apache.org/bugzilla/show_bug.cg...,contains links,https://github.com/apache/tomcat/commit/4171baf,apache/tomcat
830,CVE-2018-1284,HIVE-18879: Disallow embedded element in UDFXP...,NaN,contains links,https://github.com/apache/hive/commit/f80a38ae...,apache/hive
831,CVE-2011-3923,Fixed a security issue (see [1] for further de...,https://cwiki.apache.org/confluence/display/WW...,contains links,https://github.com/apache/struts/commit/2c1eb6...,apache/struts